# ----------------------------------------
# SITE SETTINGS
# ----------------------------------------
title: "Jason Atoms"
email: "atomstech@pm.me"
description: >-
  I’m a computer engineer focused on building streamlined software solutions
  that drive tangible results. I love pushing boundaries in web development,
  automation, and emerging tech.

baseurl: "" # Keep empty for root deployment
url: "https://jasonatoms.com" # Base site URL

# ----------------------------------------
# SEO & SOCIAL (Optional for future)
# ----------------------------------------
# twitter_username: jekyllrb
github_username: jasonatoms

# ----------------------------------------
# BUILD SETTINGS
# ----------------------------------------
theme: minima # Using Minima theme (Consider switching if customization is needed)
plugins:
  - jekyll-feed # RSS Feed Support

# Output Directory (For GitHub Pages /docs deployment)
destination: docs

# Default layout for homepage
home_layout: home

# Custom Permalink structure for blog posts
permalink: /blog/:title/

# ----------------------------------------
# COLLECTIONS & CONTENT STRUCTURE
# ----------------------------------------
collections:
  blog_posts:
    output: true
    permalink: /blog/:title/

# ----------------------------------------
# EXCLUDED FILES & DIRECTORIES
# ----------------------------------------
exclude:
  - README.md
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
